import os
import inspect
import json
from copy import deepcopy
from typing import Any, List, Optional

try:
    import torch
except ImportError:
    torch = None

try:
    from transformers import (
        AutoConfig,
        AutoModelForCausalLM,
        AutoTokenizer,
        FineGrainedFP8Config,
        Mistral3ForConditionalGeneration,
        MistralCommonBackend,
    )
except ImportError:
    AutoConfig = None
    AutoModelForCausalLM = None
    AutoTokenizer = None
    FineGrainedFP8Config = None
    Mistral3ForConditionalGeneration = None
    MistralCommonBackend = None

from config import *

QWEN25_DEFAULT_CONTEXT_WINDOW = 32768
QWEN25_MAX_CONTEXT_WINDOW = 131072
SUPPORTED_PROVIDERS = {"transformers", "openai"}
DEFAULT_OPENAI_CREDENTIAL_PATH = OPENAI_CREDENTIAL_PATH


class FallbackTextTokenizer:
    """Small tokenizer-like fallback for prompt budgeting without extra deps."""

    def encode(self, text: str, *args, **kwargs) -> list[str]:
        _ = args, kwargs
        normalized_text = "" if text is None else str(text)
        # Use short character chunks so token counts are conservative enough for truncation.
        return [normalized_text[index:index + 3] for index in range(0, len(normalized_text), 3)]

    def decode(self, token_ids: list[Any], *args, **kwargs) -> str:
        _ = args, kwargs
        return "".join(str(token_id) for token_id in token_ids)


def resolve_provider(provider: Optional[str] = None) -> str:
    requested_provider = (provider or PROVIDER).lower()
    if requested_provider in SUPPORTED_PROVIDERS:
        return requested_provider
    return "transformers"


class LLM:

    def __init__(
        self,
        model_name: Optional[str] = None,
        provider: Optional[str] = None,
        max_input_length: Optional[int] = None,
        max_generation_num: Optional[int] = None,
        think_mode: bool = False,
        query_settings: Optional[dict] = None,
        num_ctx: Optional[int] = None,
        credential_path: Optional[Any] = None,
    ):
        """
        Initialize the LLM loader.

        Parameters
        ----------
        model_name:
            The model name or path.
        provider:
            The model service provider, either "openai" or "transformers".
        max_input_length:
            The maximum number of input tokens allowed for a request.
        max_generation_num:
            The maximum number of output tokens generated by the model.
        think_mode:
            Whether to enable provider-specific thinking mode.
        query_settings:
            Provider-agnostic generation settings such as temperature, top_p, or
            provider-specific options like response_format.
        num_ctx:
            Backward-compatible alias for max_input_length.
        credential_path:
            Optional JSON credential file for OpenAI provider. If omitted,
            OPENAI_API_KEY, OPENAI_CREDENTIAL_PATH, and gpt_credential.json are
            tried in that order.
        """
        self.model_name = model_name or ANSWER_LLM_NAME
        self.provider = resolve_provider(provider)

        resolved_max_input_length = max_input_length
        if resolved_max_input_length is None:
            resolved_max_input_length = num_ctx
        if resolved_max_input_length is None:
            resolved_max_input_length = MAX_INPUT_LENGTH

        self.max_input_length = resolved_max_input_length
        self.num_ctx = self.max_input_length
        self.max_generation_num = max_generation_num or MAX_GENERATEION_NUM
        self.think_mode = think_mode
        self.current_context_window = None
        self.credential_path = (
            resolve_project_path(credential_path)
            if credential_path is not None
            else None
        )

        self.query_settings = deepcopy(
            query_settings if query_settings is not None else BASELINE_DATABASE_RETRIVAL_QUERY_SETTINGS
        )

        self.device_map = "auto"
        self.torch_dtype = None

        if self.provider == "transformers":
            self._ensure_transformers_dependencies()
            self.torch_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
            if "ministral" in self.model_name.lower():
                self._load_ministral_model()
            else:
                self._load_transformers_model()
        elif self.provider == "openai":
            self._load_openai_model()

    def _ensure_transformers_dependencies(self) -> None:
        if torch is None or AutoTokenizer is None or AutoModelForCausalLM is None:
            raise ImportError(
                "Transformers provider requires torch and transformers. Install project requirements first."
            )

    def _is_qwen25_model(self) -> bool:
        return "qwen2.5" in self.model_name.lower()

    def _get_max_context_window(self) -> int:
        return self.max_input_length + self.max_generation_num

    def _get_qwen25_context_upper_bound(self) -> int:
        return min(
            max(self._get_max_context_window(), QWEN25_DEFAULT_CONTEXT_WINDOW),
            QWEN25_MAX_CONTEXT_WINDOW,
        )

    def _resolve_qwen25_context_window(self, input_token_length: int) -> int:
        target_window = QWEN25_DEFAULT_CONTEXT_WINDOW
        upper_bound = self._get_qwen25_context_upper_bound()

        while target_window < input_token_length and target_window < upper_bound:
            target_window = min(target_window * 2, upper_bound)

        if input_token_length > target_window:
            raise ValueError(
                f"Input token length {input_token_length} exceeds the supported Qwen2.5 context window "
                f"limit {target_window}. Increase max_input_length + max_generation_num up to "
                f"{QWEN25_MAX_CONTEXT_WINDOW} or shorten the input."
            )

        return target_window

    def _reload_transformers_model_for_context(self, target_context_window: int) -> None:
        if self.current_context_window == target_context_window:
            return

        if hasattr(self, "model"):
            del self.model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        self._load_transformers_model(target_context_window=target_context_window)

    def _ensure_qwen25_context_capacity(self, input_token_length: int) -> None:
        if not self._is_qwen25_model():
            return

        target_context_window = self._resolve_qwen25_context_window(input_token_length)
        if self.current_context_window != target_context_window:
            self._reload_transformers_model_for_context(target_context_window)

    def _validate_input_length(self, input_token_length: int) -> None:
        if self._is_qwen25_model():
            self._ensure_qwen25_context_capacity(input_token_length)
            return

        if input_token_length > self._get_max_context_window():
            raise ValueError(
                f"Input token length {input_token_length} exceeds the supported context window "
                f"limit {self._get_max_context_window()}."
            )

    def _build_user_messages(self, prompt: str) -> list[dict[str, str]]:
        return [{"role": "user", "content": prompt}]

    def _build_model_inputs(self, prompt: str):
        messages = self._build_user_messages(prompt)
        if hasattr(self.tokenizer, "apply_chat_template"):
            return self.tokenizer.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_tensors="pt",
            )
        return self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=False,
        )

    def _resolve_input_tensors(self, prompt: str):
        model_inputs = self._build_model_inputs(prompt)
        if isinstance(model_inputs, torch.Tensor):
            input_ids = model_inputs
            attention_mask = torch.ones_like(input_ids)
        else:
            input_ids = model_inputs["input_ids"]
            attention_mask = model_inputs.get("attention_mask")
            if attention_mask is None:
                attention_mask = torch.ones_like(input_ids)
        return model_inputs, input_ids, attention_mask

    def count_input_tokens(self, prompt: str) -> int:
        if self.provider == "openai":
            # Include a small chat-message overhead margin. This count is used
            # for prompt fitting, not billing.
            return len(self.tokenizer.encode(prompt)) + 8

        if self.provider != "transformers":
            raise NotImplementedError(f"Prompt token counting is not implemented for provider {self.provider}.")

        _, input_ids, _ = self._resolve_input_tensors(prompt)
        return int(input_ids.shape[-1])

    def _get_last_token_logits_kwargs(self) -> dict:
        try:
            forward_signature = inspect.signature(self.model.forward)
        except (TypeError, ValueError):
            return {}

        if "logits_to_keep" in forward_signature.parameters:
            return {"logits_to_keep": 1}
        if "num_logits_to_keep" in forward_signature.parameters:
            return {"num_logits_to_keep": 1}
        return {}

    def _get_transformers_generation_kwargs(self) -> dict:
        generation_kwargs = deepcopy(self.query_settings)
        generation_kwargs.pop("max_new_tokens", None)
        generation_kwargs["max_length"] = self.max_input_length + self.max_generation_num
        do_sample = generation_kwargs.get("temperature", 0.0) > 0
        generation_kwargs["do_sample"] = do_sample
        if not do_sample:
            generation_kwargs.pop("temperature", None)
            generation_kwargs.pop("top_p", None)
            generation_kwargs.pop("top_k", None)
        generation_kwargs.setdefault("pad_token_id", self.tokenizer.pad_token_id)
        generation_kwargs.setdefault("eos_token_id", self.tokenizer.eos_token_id)
        return generation_kwargs

    def _get_openai_request_kwargs(self) -> dict:
        request_kwargs = deepcopy(self.query_settings)
        request_kwargs = {
            key: value
            for key, value in request_kwargs.items()
            if value is not None
        }
        request_kwargs.pop("repetition_penalty", None)
        request_kwargs.setdefault("max_completion_tokens", self.max_generation_num)
        request_kwargs.setdefault("temperature", 0.0)
        request_kwargs.setdefault("response_format", {"type": "json_object"})
        return request_kwargs

    def _get_openai_responses_request_kwargs(self) -> dict:
        request_kwargs = self._get_openai_request_kwargs()
        max_completion_tokens = request_kwargs.pop("max_completion_tokens", None)
        if max_completion_tokens is not None:
            request_kwargs["max_output_tokens"] = max_completion_tokens

        if self._is_gpt5_model():
            request_kwargs.pop("temperature", None)
            request_kwargs.pop("top_p", None)

        response_format = request_kwargs.pop("response_format", None)
        if isinstance(response_format, dict) and response_format.get("type") != "text":
            request_kwargs["text"] = {"format": response_format}

        return request_kwargs

    def _get_openai_chat_request_kwargs(self) -> dict:
        request_kwargs = self._get_openai_request_kwargs()
        response_format = request_kwargs.get("response_format")
        if isinstance(response_format, dict) and response_format.get("type") == "text":
            request_kwargs.pop("response_format", None)
        return request_kwargs

    def _resolve_openai_api_key(self) -> str:
        env_api_key = os.getenv("OPENAI_API_KEY")
        if env_api_key:
            return env_api_key

        credential_path = self.credential_path
        if credential_path is None and os.getenv("OPENAI_CREDENTIAL_PATH"):
            credential_path = resolve_project_path(os.environ["OPENAI_CREDENTIAL_PATH"])
        if credential_path is None and DEFAULT_OPENAI_CREDENTIAL_PATH.is_file():
            credential_path = DEFAULT_OPENAI_CREDENTIAL_PATH

        if credential_path is None:
            raise ValueError(
                "OpenAI provider requires OPENAI_API_KEY or a credential JSON file."
            )
        if not credential_path.is_file():
            raise FileNotFoundError(f"OpenAI credential file not found: {credential_path}")

        credentials = json.loads(credential_path.read_text(encoding="utf-8"))
        if not isinstance(credentials, dict):
            raise ValueError(f"OpenAI credential file must contain a JSON object: {credential_path}")

        for key_name in ("api_key", "openai_api_key", "OPENAI_API_KEY", "key"):
            api_key = credentials.get(key_name)
            if isinstance(api_key, str) and api_key.strip():
                return api_key.strip()

        raise ValueError(
            f"OpenAI credential file must contain one of: api_key, openai_api_key, OPENAI_API_KEY, key."
        )

    def _load_openai_tokenizer(self):
        try:
            import tiktoken

            try:
                return tiktoken.encoding_for_model(self.model_name)
            except KeyError:
                return tiktoken.get_encoding("o200k_base")
        except ImportError:
            return FallbackTextTokenizer()

    def _load_openai_model(self):
        try:
            import openai
        except ImportError as exc:
            raise ImportError(
                "OpenAI provider requires the openai package. Install project requirements first."
            ) from exc

        self.client = openai.OpenAI(api_key=self._resolve_openai_api_key())
        self.tokenizer = self._load_openai_tokenizer()
        self.current_context_window = self.max_input_length + self.max_generation_num

    def _is_gpt5_model(self) -> bool:
        return self.model_name.lower().startswith("gpt-5")

    def _extract_openai_response_text(self, response) -> str:
        output_text = getattr(response, "output_text", None)
        if isinstance(output_text, str):
            return output_text.strip()

        output_parts: list[str] = []
        for output_item in getattr(response, "output", []) or []:
            for content_item in getattr(output_item, "content", []) or []:
                text_value = getattr(content_item, "text", None)
                if isinstance(text_value, str):
                    output_parts.append(text_value)
        return "".join(output_parts).strip()

    def _extract_openai_usage_tokens(self, response) -> int:
        usage = getattr(response, "usage", None)
        if usage is None:
            return 0

        total_tokens = getattr(usage, "total_tokens", None)
        if total_tokens is not None:
            return int(total_tokens or 0)

        input_tokens = int(getattr(usage, "input_tokens", 0) or 0)
        output_tokens = int(getattr(usage, "output_tokens", 0) or 0)
        return input_tokens + output_tokens

    def _load_ministral_model(self):
        self.tokenizer = MistralCommonBackend.from_pretrained(self.model_name)
        self.model = Mistral3ForConditionalGeneration.from_pretrained(
            self.model_name,
            device_map=self.device_map,
            quantization_config=FineGrainedFP8Config(dequantize=True),
        )

        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.current_context_window = self.max_input_length

    def _query_ministral(self, prompt: str, output_hidden_states: bool = False):
        response, _ = self._query_ministral_with_usage(
            prompt,
            output_hidden_states=output_hidden_states,
        )
        return response

    def _query_ministral_with_usage(self, prompt: str, output_hidden_states: bool = False):
        model_inputs, input_ids, attention_mask = self._resolve_input_tensors(prompt)
        model_inputs = model_inputs.to(self.model.device)
        input_ids = model_inputs["input_ids"]
        attention_mask = model_inputs.get("attention_mask", attention_mask).to(self.model.device)

        self._validate_input_length(input_ids.shape[-1])
        generation_kwargs = self._get_transformers_generation_kwargs()
        input_token_count = int(input_ids.shape[-1])

        if output_hidden_states:
            with torch.inference_mode():
                outputs = self.model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=False,
                    use_cache=False,
                    return_dict=True,
                    **self._get_last_token_logits_kwargs(),
                )
            return outputs.logits[:, -1, :].float(), input_token_count

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                use_cache=True,
                **generation_kwargs,
            )
        generated_tokens = outputs[0][input_ids.shape[-1]:]
        output_token_count = int(generated_tokens.shape[-1])
        return (
            self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip(),
            input_token_count + output_token_count,
        )

    def _load_transformers_model(self, target_context_window: Optional[int] = None):
        """Load a local or Hugging Face causal language model."""
        if not hasattr(self, "tokenizer"):
            self.tokenizer = AutoTokenizer.from_pretrained(
                self.model_name,
                trust_remote_code=True,
            )

        model_kwargs = {
            "torch_dtype": self.torch_dtype,
            "device_map": self.device_map,
            "trust_remote_code": True,
        }

        resolved_context_window = target_context_window
        if self._is_qwen25_model():
            if resolved_context_window is None:
                resolved_context_window = min(
                    max(self.max_input_length + self.max_generation_num, QWEN25_DEFAULT_CONTEXT_WINDOW),
                    QWEN25_MAX_CONTEXT_WINDOW,
                )

            self.current_context_window = resolved_context_window

            if resolved_context_window > QWEN25_DEFAULT_CONTEXT_WINDOW:
                config = AutoConfig.from_pretrained(
                    self.model_name,
                    trust_remote_code=True,
                )
                original_rope_scaling = dict(getattr(config, "rope_scaling", {}) or {})
                config.rope_scaling = {
                    **original_rope_scaling,
                    "rope_type": "yarn",
                    "type": "yarn",
                    "factor": resolved_context_window / QWEN25_DEFAULT_CONTEXT_WINDOW,
                    "original_max_position_embeddings": QWEN25_DEFAULT_CONTEXT_WINDOW,
                }
                # Keep generate() length checks aligned with the expanded YaRN window.
                config.max_position_embeddings = resolved_context_window
                model_kwargs["config"] = config
        else:
            self.current_context_window = self._get_max_context_window()

        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_name,
            **model_kwargs,
        )

        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

    def _query_transformers(self, prompt: str, output_hidden_states: bool = False):
        """Call a local transformers model to generate text."""
        response, _ = self._query_transformers_with_usage(
            prompt,
            output_hidden_states=output_hidden_states,
        )
        return response

    def _query_transformers_with_usage(self, prompt: str, output_hidden_states: bool = False):
        """Call a local transformers model and return response plus total token usage."""
        _, input_ids, attention_mask = self._resolve_input_tensors(prompt)
        self._validate_input_length(input_ids.shape[-1])

        input_ids = input_ids.to(self.model.device)
        attention_mask = attention_mask.to(self.model.device)
        generation_kwargs = self._get_transformers_generation_kwargs()
        input_token_count = int(input_ids.shape[-1])

        if output_hidden_states:
            with torch.inference_mode():
                outputs = self.model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=False,
                    use_cache=False,
                    return_dict=True,
                    **self._get_last_token_logits_kwargs(),
                )
            return outputs.logits[:, -1, :].float(), input_token_count

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                use_cache=True,
                **generation_kwargs,
            )
        generated_tokens = outputs[0][input_ids.shape[-1]:]
        output_token_count = int(generated_tokens.shape[-1])
        return (
            self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip(),
            input_token_count + output_token_count,
        )

    def _query_openai(self, prompt: str) -> str:
        """Call the OpenAI API to generate text."""
        response_text, _ = self._query_openai_with_usage(prompt)
        return response_text

    def _query_openai_with_usage(self, prompt: str) -> tuple[str, int]:
        if self._is_gpt5_model() and hasattr(self.client, "responses"):
            response = self.client.responses.create(
                model=self.model_name,
                input=self._build_user_messages(prompt),
                **self._get_openai_responses_request_kwargs(),
            )
            return (
                self._extract_openai_response_text(response),
                self._extract_openai_usage_tokens(response),
            )

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=self._build_user_messages(prompt),
            **self._get_openai_chat_request_kwargs(),
        )
        response_text = response.choices[0].message.content or ""
        total_tokens = self._extract_openai_usage_tokens(response)
        return response_text, total_tokens

    def batch_query(self, prompts: List[str], use_cache: bool = True) -> List[str]:
        """
        Batch query multiple prompts.

        Parameters
        ----------
        prompts:
            Prompt list.
        use_cache:
            Reserved for backward compatibility.
        """
        _ = use_cache
        return [self.query(prompt) for prompt in prompts]

    def query_with_usage(self, prompt: str) -> tuple[str, int]:
        provider = self.provider
        if provider == "openai":
            return self._query_openai_with_usage(prompt)
        if provider == "transformers":
            if "ministral" in self.model_name.lower():
                return self._query_ministral_with_usage(prompt)
            return self._query_transformers_with_usage(prompt)
        raise ValueError(f"Unsupported LLM provider: {provider}")

    def query_logits_with_usage(self, prompt: str):
        if self.provider != "transformers":
            raise NotImplementedError(
                f"Logits queries are currently only implemented for transformers models, got {self.provider}."
            )
        if "ministral" in self.model_name.lower():
            return self._query_ministral_with_usage(prompt, output_hidden_states=True)
        return self._query_transformers_with_usage(prompt, output_hidden_states=True)

    def query(self, prompt: str) -> str:
        response_text, _ = self.query_with_usage(prompt)
        return response_text


if __name__ == "__main__":

    llm = LLM(model_name="Qwen/Qwen2.5-7B-Instruct", provider="transformers")
    print(f"Initialize {llm.model_name} on {llm.device_map}, provider={llm.provider}")
    query = "What is the capital of France?"
    query_list = ["What is the president of UK?", "How long you have been alive?"]

    response = llm.query(query)
    print(f"Query: {query}\n{llm.model_name} Response: {response}")

    # responses = llm.batch_query(query_list)
    # for q, a in zip(query_list, responses):
    #     print(f"Query: {q}\n{llm.model_name} Response: {a}")
