import os
from copy import deepcopy
from typing import List, Optional

import ollama
import openai
import torch
from transformers import (
    AutoConfig,
    AutoModelForCausalLM,
    AutoTokenizer,
    FineGrainedFP8Config,
    Mistral3ForConditionalGeneration,
    MistralCommonBackend,
)

from config import *

QWEN25_DEFAULT_CONTEXT_WINDOW = 32768
QWEN25_MAX_CONTEXT_WINDOW = 131072


class LLM:

    def __init__(
        self,
        model_name: Optional[str] = None,
        provider: Optional[str] = None,
        max_input_length: Optional[int] = None,
        max_generation_num: Optional[int] = None,
        think_mode: bool = False,
        query_settings: Optional[dict] = None,
        num_ctx: Optional[int] = None,
    ):
        """
        Initialize the LLM loader.

        Parameters
        ----------
        model_name:
            The model name or path.
        provider:
            The model service provider, such as "openai", "ollama", or "transformers".
        max_input_length:
            The maximum number of input tokens allowed for a request.
        max_generation_num:
            The maximum number of output tokens generated by the model.
        think_mode:
            Whether to enable provider-specific thinking mode.
        query_settings:
            Provider-agnostic generation settings such as temperature, top_p, or
            provider-specific options like response_format / format.
        num_ctx:
            Backward-compatible alias for max_input_length.
        """
        self.model_name = model_name or ANSWER_LLM_NAME
        self.provider = (provider or PROVIDER).lower()

        resolved_max_input_length = max_input_length
        if resolved_max_input_length is None:
            resolved_max_input_length = num_ctx
        if resolved_max_input_length is None:
            resolved_max_input_length = MAX_INPUT_LENGTH

        self.max_input_length = resolved_max_input_length
        self.num_ctx = self.max_input_length
        self.max_generation_num = max_generation_num or MAX_GENERATEION_NUM
        self.think_mode = think_mode
        self.current_context_window = None

        self.query_settings = deepcopy(
            query_settings if query_settings is not None else BASELINE_DATABASE_RETRIVAL_QUERY_SETTINGS
        )

        self.torch_dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
        self.device_map = "auto"

        if self.provider == "transformers":
            if "ministral" in self.model_name.lower():
                self._load_ministral_model()
            else:
                self._load_transformers_model()

    def _is_qwen25_model(self) -> bool:
        return "qwen2.5" in self.model_name.lower()

    def _get_max_context_window(self) -> int:
        return self.max_input_length + self.max_generation_num

    def _get_qwen25_context_upper_bound(self) -> int:
        return min(
            max(self._get_max_context_window(), QWEN25_DEFAULT_CONTEXT_WINDOW),
            QWEN25_MAX_CONTEXT_WINDOW,
        )

    def _resolve_qwen25_context_window(self, input_token_length: int) -> int:
        target_window = QWEN25_DEFAULT_CONTEXT_WINDOW
        upper_bound = self._get_qwen25_context_upper_bound()

        while target_window < input_token_length and target_window < upper_bound:
            target_window = min(target_window * 2, upper_bound)

        if input_token_length > target_window:
            raise ValueError(
                f"Input token length {input_token_length} exceeds the supported Qwen2.5 context window "
                f"limit {target_window}. Increase max_input_length + max_generation_num up to "
                f"{QWEN25_MAX_CONTEXT_WINDOW} or shorten the input."
            )

        return target_window

    def _reload_transformers_model_for_context(self, target_context_window: int) -> None:
        if self.current_context_window == target_context_window:
            return

        if hasattr(self, "model"):
            del self.model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        self._load_transformers_model(target_context_window=target_context_window)

    def _ensure_qwen25_context_capacity(self, input_token_length: int) -> None:
        if not self._is_qwen25_model():
            return

        target_context_window = self._resolve_qwen25_context_window(input_token_length)
        if self.current_context_window != target_context_window:
            self._reload_transformers_model_for_context(target_context_window)

    def _validate_input_length(self, input_token_length: int) -> None:
        if self._is_qwen25_model():
            self._ensure_qwen25_context_capacity(input_token_length)
            return

        if input_token_length > self._get_max_context_window():
            raise ValueError(
                f"Input token length {input_token_length} exceeds the supported context window "
                f"limit {self._get_max_context_window()}."
            )

    def count_input_tokens(self, prompt: str) -> int:
        messages = [{"role": "user", "content": prompt}]

        if self.provider != "transformers":
            raise NotImplementedError(
                f"Prompt token counting is currently only implemented for transformers models, got {self.provider}."
            )

        if hasattr(self.tokenizer, "apply_chat_template"):
            model_inputs = self.tokenizer.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_tensors="pt",
            )
        else:
            model_inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=False,
            )

        if isinstance(model_inputs, torch.Tensor):
            return int(model_inputs.shape[-1])

        return int(model_inputs["input_ids"].shape[-1])

    def _get_transformers_generation_kwargs(self) -> dict:
        generation_kwargs = deepcopy(self.query_settings)
        generation_kwargs.pop("max_new_tokens", None)
        generation_kwargs["max_length"] = self.max_input_length + self.max_generation_num
        do_sample = generation_kwargs.get("temperature", 0.0) > 0
        generation_kwargs["do_sample"] = do_sample
        if not do_sample:
            generation_kwargs.pop("temperature", None)
            generation_kwargs.pop("top_p", None)
            generation_kwargs.pop("top_k", None)
        generation_kwargs.setdefault("pad_token_id", self.tokenizer.pad_token_id)
        generation_kwargs.setdefault("eos_token_id", self.tokenizer.eos_token_id)
        return generation_kwargs

    def _get_openai_request_kwargs(self) -> dict:
        request_kwargs = deepcopy(self.query_settings)
        request_kwargs.setdefault("max_completion_tokens", self.max_generation_num)
        request_kwargs.setdefault("temperature", 0.0)
        request_kwargs.setdefault("response_format", {"type": "json_object"})
        return request_kwargs

    def _get_ollama_request_kwargs(self) -> tuple[Optional[str], dict]:
        options = deepcopy(self.query_settings)
        response_format = options.pop("format", "json")
        options["num_ctx"] = self.max_input_length
        options.setdefault("num_predict", self.max_generation_num)
        return response_format, options

    def _load_ministral_model(self):
        self.tokenizer = MistralCommonBackend.from_pretrained(self.model_name)
        self.model = Mistral3ForConditionalGeneration.from_pretrained(
            self.model_name,
            device_map=self.device_map,
            quantization_config=FineGrainedFP8Config(dequantize=True),
        )

        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.current_context_window = self.max_input_length

    def _query_ministral(self, prompt: str, output_hidden_states: bool = False):
        messages = [{"role": "user", "content": prompt}]
        model_inputs = self.tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
        )
        model_inputs = model_inputs.to(self.model.device)
        input_ids = model_inputs["input_ids"]
        attention_mask = model_inputs.get("attention_mask")
        if attention_mask is None:
            attention_mask = torch.ones_like(input_ids)

        self._validate_input_length(input_ids.shape[-1])
        generation_kwargs = self._get_transformers_generation_kwargs()

        if output_hidden_states:
            with torch.inference_mode():
                outputs = self.model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=False,
                    use_cache=False,
                    return_dict=True,
                )
            return outputs.logits[:, -1, :].float()

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                use_cache=True,
                **generation_kwargs,
            )
        generated_tokens = outputs[0][input_ids.shape[-1]:]
        return self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()

    def _load_transformers_model(self, target_context_window: Optional[int] = None):
        """Load a local or Hugging Face causal language model."""
        if not hasattr(self, "tokenizer"):
            self.tokenizer = AutoTokenizer.from_pretrained(
                self.model_name,
                trust_remote_code=True,
            )

        model_kwargs = {
            "torch_dtype": self.torch_dtype,
            "device_map": self.device_map,
            "trust_remote_code": True,
        }

        resolved_context_window = target_context_window
        if self._is_qwen25_model():
            if resolved_context_window is None:
                resolved_context_window = min(
                    max(self.max_input_length + self.max_generation_num, QWEN25_DEFAULT_CONTEXT_WINDOW),
                    QWEN25_MAX_CONTEXT_WINDOW,
                )

            self.current_context_window = resolved_context_window

            if resolved_context_window > QWEN25_DEFAULT_CONTEXT_WINDOW:
                config = AutoConfig.from_pretrained(
                    self.model_name,
                    trust_remote_code=True,
                )
                original_rope_scaling = dict(getattr(config, "rope_scaling", {}) or {})
                config.rope_scaling = {
                    **original_rope_scaling,
                    "rope_type": "yarn",
                    "type": "yarn",
                    "factor": resolved_context_window / QWEN25_DEFAULT_CONTEXT_WINDOW,
                    "original_max_position_embeddings": QWEN25_DEFAULT_CONTEXT_WINDOW,
                }
                # Keep generate() length checks aligned with the expanded YaRN window.
                config.max_position_embeddings = resolved_context_window
                model_kwargs["config"] = config
        else:
            self.current_context_window = self._get_max_context_window()

        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_name,
            **model_kwargs,
        )

        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

    def _query_transformers(self, prompt: str, output_hidden_states: bool = False):
        """Call a local transformers model to generate text."""
        messages = [{"role": "user", "content": prompt}]

        if hasattr(self.tokenizer, "apply_chat_template"):
            model_inputs = self.tokenizer.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_tensors="pt",
            )
        else:
            model_inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=False,
            )

        if isinstance(model_inputs, torch.Tensor):
            input_ids = model_inputs
            attention_mask = torch.ones_like(input_ids)
        else:
            input_ids = model_inputs["input_ids"]
            attention_mask = model_inputs.get("attention_mask")
            if attention_mask is None:
                attention_mask = torch.ones_like(input_ids)

        self._validate_input_length(input_ids.shape[-1])

        input_ids = input_ids.to(self.model.device)
        attention_mask = attention_mask.to(self.model.device)
        generation_kwargs = self._get_transformers_generation_kwargs()

        if output_hidden_states:
            with torch.inference_mode():
                outputs = self.model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    output_hidden_states=False,
                    use_cache=False,
                    return_dict=True,
                )
            return outputs.logits[:, -1, :].float()

        with torch.no_grad():
            outputs = self.model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                use_cache=True,
                **generation_kwargs,
            )
        generated_tokens = outputs[0][input_ids.shape[-1]:]
        return self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()

    def _query_openai(self, prompt: str) -> str:
        """Call the OpenAI API to generate text."""
        client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = client.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            **self._get_openai_request_kwargs(),
        )
        return response.choices[0].message.content

    def _query_ollama(self, prompt: str) -> str:
        """Call a local Ollama model to generate text."""
        response_format, options = self._get_ollama_request_kwargs()
        response = ollama.chat(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            format=response_format,
            think=self.think_mode,
            options=options,
        )
        return response["message"]["content"]

    def batch_query(self, prompts: List[str], use_cache: bool = True) -> List[str]:
        """
        Batch query multiple prompts.

        Parameters
        ----------
        prompts:
            Prompt list.
        use_cache:
            Reserved for backward compatibility.
        """
        _ = use_cache
        return [self.query(prompt) for prompt in prompts]

    def query(self, prompt: str) -> str:
        provider = self.provider
        if provider == "ollama":
            return self._query_ollama(prompt)
        if provider == "openai":
            return self._query_openai(prompt)
        if provider == "transformers":
            if "ministral" in self.model_name.lower():
                return self._query_ministral(prompt)
            return self._query_transformers(prompt)
        raise ValueError(f"Unsupported LLM provider: {provider}")


if __name__ == "__main__":

    llm = LLM(model_name="Qwen/Qwen2.5-7B-Instruct", provider="transformers")
    print(f"Initialize {llm.model_name} on {llm.device_map}, provider={llm.provider}")
    query = "What is the capital of France?"
    query_list = ["What is the president of UK?", "How long you have been alive?"]

    response = llm.query(query)
    print(f"Query: {query}\n{llm.model_name} Response: {response}")

    # responses = llm.batch_query(query_list)
    # for q, a in zip(query_list, responses):
    #     print(f"Query: {q}\n{llm.model_name} Response: {a}")
